language: node_js
node_js:
  - "6"
before_install:
  - npm install -g sequelize-cli@2.8.0
  - npm install -g mocha

before_script:
  - npm install
  - psql -c 'create database "HelloBooks-test";' -U postgres

script:
  - npm run test

after_success:
  - npm install codeclimate-test-reporter -g
  - npm run coverage

addons:
  code_climate:
    repo_token: 158a6238e20cb8e6e02f0c613bdab880ec35840c6518d22a59d94d2be8c66fa2
    